# Generated by Django 3.0.7 on 2020-07-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.IntegerField(default=-1),
        ),
    ]
