# Generated by Django 3.0.7 on 2020-06-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200622_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mens'), ('W', 'Womens'), ('G', 'Girls'), ('B', 'Boys')], max_length=2),
        ),
    ]
