# Generated by Django 3.0.7 on 2020-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200622_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is a description of the current item. Descriptions are meant to tell the user more about our products.', max_length=200),
        ),
    ]
